// source: weave/trait/description.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.weave.trait.description.DeviceIdentityTrait', null, global);
goog.exportSymbol('proto.weave.trait.description.Float_Indirect', null, global);
goog.exportSymbol('proto.weave.trait.description.Int32_Indirect', null, global);
goog.exportSymbol('proto.weave.trait.description.String_Indirect', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weave.trait.description.DeviceIdentityTrait = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weave.trait.description.DeviceIdentityTrait, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weave.trait.description.DeviceIdentityTrait.displayName = 'proto.weave.trait.description.DeviceIdentityTrait';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weave.trait.description.String_Indirect = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weave.trait.description.String_Indirect, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weave.trait.description.String_Indirect.displayName = 'proto.weave.trait.description.String_Indirect';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weave.trait.description.Float_Indirect = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weave.trait.description.Float_Indirect, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weave.trait.description.Float_Indirect.displayName = 'proto.weave.trait.description.Float_Indirect';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weave.trait.description.Int32_Indirect = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weave.trait.description.Int32_Indirect, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weave.trait.description.Int32_Indirect.displayName = 'proto.weave.trait.description.Int32_Indirect';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.toObject = function(opt_includeInstance) {
  return proto.weave.trait.description.DeviceIdentityTrait.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weave.trait.description.DeviceIdentityTrait} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.DeviceIdentityTrait.toObject = function(includeInstance, msg) {
  var f, obj = {
    manufacturer: (f = msg.getManufacturer()) && proto.weave.trait.description.String_Indirect.toObject(includeInstance, f),
    modelName: (f = msg.getModelName()) && proto.weave.trait.description.String_Indirect.toObject(includeInstance, f),
    serialNumber: jspb.Message.getFieldWithDefault(msg, 6, ""),
    fwVersion: jspb.Message.getFieldWithDefault(msg, 7, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weave.trait.description.DeviceIdentityTrait}
 */
proto.weave.trait.description.DeviceIdentityTrait.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weave.trait.description.DeviceIdentityTrait;
  return proto.weave.trait.description.DeviceIdentityTrait.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weave.trait.description.DeviceIdentityTrait} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weave.trait.description.DeviceIdentityTrait}
 */
proto.weave.trait.description.DeviceIdentityTrait.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new proto.weave.trait.description.String_Indirect;
      reader.readMessage(value,proto.weave.trait.description.String_Indirect.deserializeBinaryFromReader);
      msg.setManufacturer(value);
      break;
    case 4:
      var value = new proto.weave.trait.description.String_Indirect;
      reader.readMessage(value,proto.weave.trait.description.String_Indirect.deserializeBinaryFromReader);
      msg.setModelName(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSerialNumber(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setFwVersion(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weave.trait.description.DeviceIdentityTrait.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weave.trait.description.DeviceIdentityTrait} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.DeviceIdentityTrait.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getManufacturer();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.weave.trait.description.String_Indirect.serializeBinaryToWriter
    );
  }
  f = message.getModelName();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.weave.trait.description.String_Indirect.serializeBinaryToWriter
    );
  }
  f = message.getSerialNumber();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getFwVersion();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
};


/**
 * optional String_Indirect manufacturer = 2;
 * @return {?proto.weave.trait.description.String_Indirect}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.getManufacturer = function() {
  return /** @type{?proto.weave.trait.description.String_Indirect} */ (
    jspb.Message.getWrapperField(this, proto.weave.trait.description.String_Indirect, 2));
};


/**
 * @param {?proto.weave.trait.description.String_Indirect|undefined} value
 * @return {!proto.weave.trait.description.DeviceIdentityTrait} returns this
*/
proto.weave.trait.description.DeviceIdentityTrait.prototype.setManufacturer = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.description.DeviceIdentityTrait} returns this
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.clearManufacturer = function() {
  return this.setManufacturer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.hasManufacturer = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional String_Indirect model_name = 4;
 * @return {?proto.weave.trait.description.String_Indirect}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.getModelName = function() {
  return /** @type{?proto.weave.trait.description.String_Indirect} */ (
    jspb.Message.getWrapperField(this, proto.weave.trait.description.String_Indirect, 4));
};


/**
 * @param {?proto.weave.trait.description.String_Indirect|undefined} value
 * @return {!proto.weave.trait.description.DeviceIdentityTrait} returns this
*/
proto.weave.trait.description.DeviceIdentityTrait.prototype.setModelName = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.description.DeviceIdentityTrait} returns this
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.clearModelName = function() {
  return this.setModelName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.hasModelName = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string serial_number = 6;
 * @return {string}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.getSerialNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.weave.trait.description.DeviceIdentityTrait} returns this
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.setSerialNumber = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string fw_version = 7;
 * @return {string}
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.getFwVersion = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.weave.trait.description.DeviceIdentityTrait} returns this
 */
proto.weave.trait.description.DeviceIdentityTrait.prototype.setFwVersion = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weave.trait.description.String_Indirect.prototype.toObject = function(opt_includeInstance) {
  return proto.weave.trait.description.String_Indirect.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weave.trait.description.String_Indirect} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.String_Indirect.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weave.trait.description.String_Indirect}
 */
proto.weave.trait.description.String_Indirect.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weave.trait.description.String_Indirect;
  return proto.weave.trait.description.String_Indirect.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weave.trait.description.String_Indirect} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weave.trait.description.String_Indirect}
 */
proto.weave.trait.description.String_Indirect.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weave.trait.description.String_Indirect.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weave.trait.description.String_Indirect.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weave.trait.description.String_Indirect} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.String_Indirect.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string value = 1;
 * @return {string}
 */
proto.weave.trait.description.String_Indirect.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.weave.trait.description.String_Indirect} returns this
 */
proto.weave.trait.description.String_Indirect.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weave.trait.description.Float_Indirect.prototype.toObject = function(opt_includeInstance) {
  return proto.weave.trait.description.Float_Indirect.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weave.trait.description.Float_Indirect} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.Float_Indirect.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weave.trait.description.Float_Indirect}
 */
proto.weave.trait.description.Float_Indirect.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weave.trait.description.Float_Indirect;
  return proto.weave.trait.description.Float_Indirect.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weave.trait.description.Float_Indirect} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weave.trait.description.Float_Indirect}
 */
proto.weave.trait.description.Float_Indirect.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weave.trait.description.Float_Indirect.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weave.trait.description.Float_Indirect.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weave.trait.description.Float_Indirect} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.Float_Indirect.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0.0) {
    writer.writeFloat(
      1,
      f
    );
  }
};


/**
 * optional float value = 1;
 * @return {number}
 */
proto.weave.trait.description.Float_Indirect.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.weave.trait.description.Float_Indirect} returns this
 */
proto.weave.trait.description.Float_Indirect.prototype.setValue = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weave.trait.description.Int32_Indirect.prototype.toObject = function(opt_includeInstance) {
  return proto.weave.trait.description.Int32_Indirect.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weave.trait.description.Int32_Indirect} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.Int32_Indirect.toObject = function(includeInstance, msg) {
  var f, obj = {
    value: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weave.trait.description.Int32_Indirect}
 */
proto.weave.trait.description.Int32_Indirect.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weave.trait.description.Int32_Indirect;
  return proto.weave.trait.description.Int32_Indirect.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weave.trait.description.Int32_Indirect} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weave.trait.description.Int32_Indirect}
 */
proto.weave.trait.description.Int32_Indirect.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weave.trait.description.Int32_Indirect.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weave.trait.description.Int32_Indirect.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weave.trait.description.Int32_Indirect} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.description.Int32_Indirect.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getValue();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 value = 1;
 * @return {number}
 */
proto.weave.trait.description.Int32_Indirect.prototype.getValue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.weave.trait.description.Int32_Indirect} returns this
 */
proto.weave.trait.description.Int32_Indirect.prototype.setValue = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


goog.object.extend(exports, proto.weave.trait.description);
