// source: weave/trait/heartbeat.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.weave.trait.heartbeat.LivenessTrait', null, global);
goog.exportSymbol('proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent', null, global);
goog.exportSymbol('proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weave.trait.heartbeat.LivenessTrait = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weave.trait.heartbeat.LivenessTrait, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weave.trait.heartbeat.LivenessTrait.displayName = 'proto.weave.trait.heartbeat.LivenessTrait';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.displayName = 'proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.toObject = function(opt_includeInstance) {
  return proto.weave.trait.heartbeat.LivenessTrait.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weave.trait.heartbeat.LivenessTrait} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.heartbeat.LivenessTrait.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    timestatuschanged: (f = msg.getTimestatuschanged()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    maxinactivityduration: (f = msg.getMaxinactivityduration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    heartbeatstatus: jspb.Message.getFieldWithDefault(msg, 4, 0),
    timeheartbeatstatuschanged: (f = msg.getTimeheartbeatstatuschanged()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    notifyrequestunresponsiveness: (f = msg.getNotifyrequestunresponsiveness()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    notifyrequestunresponsivenesstimestatuschanged: (f = msg.getNotifyrequestunresponsivenesstimestatuschanged()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    commandrequestunresponsiveness: (f = msg.getCommandrequestunresponsiveness()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    commandrequestunresponsivenesstimestatuschanged: (f = msg.getCommandrequestunresponsivenesstimestatuschanged()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait}
 */
proto.weave.trait.heartbeat.LivenessTrait.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weave.trait.heartbeat.LivenessTrait;
  return proto.weave.trait.heartbeat.LivenessTrait.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weave.trait.heartbeat.LivenessTrait} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait}
 */
proto.weave.trait.heartbeat.LivenessTrait.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimestatuschanged(value);
      break;
    case 3:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setMaxinactivityduration(value);
      break;
    case 4:
      var value = /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (reader.readEnum());
      msg.setHeartbeatstatus(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setTimeheartbeatstatuschanged(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setNotifyrequestunresponsiveness(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setNotifyrequestunresponsivenesstimestatuschanged(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setCommandrequestunresponsiveness(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCommandrequestunresponsivenesstimestatuschanged(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weave.trait.heartbeat.LivenessTrait.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weave.trait.heartbeat.LivenessTrait} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.heartbeat.LivenessTrait.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTimestatuschanged();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getMaxinactivityduration();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getHeartbeatstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getTimeheartbeatstatuschanged();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getNotifyrequestunresponsiveness();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getNotifyrequestunresponsivenesstimestatuschanged();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCommandrequestunresponsiveness();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getCommandrequestunresponsivenesstimestatuschanged();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus = {
  LIVENESS_DEVICE_STATUS_UNSPECIFIED: 0,
  LIVENESS_DEVICE_STATUS_ONLINE: 1,
  LIVENESS_DEVICE_STATUS_UNREACHABLE: 2,
  LIVENESS_DEVICE_STATUS_UNINITIALIZED: 3,
  LIVENESS_DEVICE_STATUS_REBOOTING: 4,
  LIVENESS_DEVICE_STATUS_UPGRADING: 5,
  LIVENESS_DEVICE_STATUS_SCHEDULED_DOWN: 6
};




if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    heartbeatstatus: jspb.Message.getFieldWithDefault(msg, 2, 0),
    notifyrequestunresponsiveness: (f = msg.getNotifyrequestunresponsiveness()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    commandrequestunresponsiveness: (f = msg.getCommandrequestunresponsiveness()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    prevstatus: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent;
  return proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (reader.readEnum());
      msg.setHeartbeatstatus(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setNotifyrequestunresponsiveness(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setCommandrequestunresponsiveness(value);
      break;
    case 5:
      var value = /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (reader.readEnum());
      msg.setPrevstatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getHeartbeatstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getNotifyrequestunresponsiveness();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getCommandrequestunresponsiveness();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getPrevstatus();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * optional LivenessDeviceStatus status = 1;
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.getStatus = function() {
  return /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional LivenessDeviceStatus heartbeatStatus = 2;
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.getHeartbeatstatus = function() {
  return /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.setHeartbeatstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional google.protobuf.BoolValue notifyRequestUnresponsiveness = 3;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.getNotifyrequestunresponsiveness = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 3));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.setNotifyrequestunresponsiveness = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.clearNotifyrequestunresponsiveness = function() {
  return this.setNotifyrequestunresponsiveness(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.hasNotifyrequestunresponsiveness = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.BoolValue commandRequestUnresponsiveness = 4;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.getCommandrequestunresponsiveness = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 4));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.setCommandrequestunresponsiveness = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.clearCommandrequestunresponsiveness = function() {
  return this.setCommandrequestunresponsiveness(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.hasCommandrequestunresponsiveness = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional LivenessDeviceStatus prevStatus = 5;
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus}
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.getPrevstatus = function() {
  return /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.LivenessChangeEvent.prototype.setPrevstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional LivenessDeviceStatus status = 1;
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getStatus = function() {
  return /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional google.protobuf.Timestamp timeStatusChanged = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getTimestatuschanged = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.prototype.setTimestatuschanged = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.clearTimestatuschanged = function() {
  return this.setTimestatuschanged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.hasTimestatuschanged = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.Duration maxInactivityDuration = 3;
 * @return {?proto.google.protobuf.Duration}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getMaxinactivityduration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 3));
};


/**
 * @param {?proto.google.protobuf.Duration|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.prototype.setMaxinactivityduration = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.clearMaxinactivityduration = function() {
  return this.setMaxinactivityduration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.hasMaxinactivityduration = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional LivenessDeviceStatus heartbeatStatus = 4;
 * @return {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getHeartbeatstatus = function() {
  return /** @type {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.weave.trait.heartbeat.LivenessTrait.LivenessDeviceStatus} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.setHeartbeatstatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional google.protobuf.Timestamp timeHeartbeatStatusChanged = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getTimeheartbeatstatuschanged = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.prototype.setTimeheartbeatstatuschanged = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.clearTimeheartbeatstatuschanged = function() {
  return this.setTimeheartbeatstatuschanged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.hasTimeheartbeatstatuschanged = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.BoolValue notifyRequestUnresponsiveness = 6;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getNotifyrequestunresponsiveness = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 6));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.prototype.setNotifyrequestunresponsiveness = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.clearNotifyrequestunresponsiveness = function() {
  return this.setNotifyrequestunresponsiveness(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.hasNotifyrequestunresponsiveness = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp notifyRequestUnresponsivenessTimeStatusChanged = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getNotifyrequestunresponsivenesstimestatuschanged = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.prototype.setNotifyrequestunresponsivenesstimestatuschanged = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.clearNotifyrequestunresponsivenesstimestatuschanged = function() {
  return this.setNotifyrequestunresponsivenesstimestatuschanged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.hasNotifyrequestunresponsivenesstimestatuschanged = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.BoolValue commandRequestUnresponsiveness = 8;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getCommandrequestunresponsiveness = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 8));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.prototype.setCommandrequestunresponsiveness = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.clearCommandrequestunresponsiveness = function() {
  return this.setCommandrequestunresponsiveness(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.hasCommandrequestunresponsiveness = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp commandRequestUnresponsivenessTimeStatusChanged = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.getCommandrequestunresponsivenesstimestatuschanged = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
*/
proto.weave.trait.heartbeat.LivenessTrait.prototype.setCommandrequestunresponsivenesstimestatuschanged = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.weave.trait.heartbeat.LivenessTrait} returns this
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.clearCommandrequestunresponsivenesstimestatuschanged = function() {
  return this.setCommandrequestunresponsivenesstimestatuschanged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.weave.trait.heartbeat.LivenessTrait.prototype.hasCommandrequestunresponsivenesstimestatuschanged = function() {
  return jspb.Message.getField(this, 9) != null;
};


goog.object.extend(exports, proto.weave.trait.heartbeat);
